# Boolean indexing

In [2]:
#create 3x2 array
import numpy as np

In [3]:
an_array = np.array([[1,3],[4,5],[8,9]])

In [4]:
an_array

array([[1, 3],
       [4, 5],
       [8, 9]])

In [7]:
#create a filter which will be boolean values for whether each element meets 
filter = (an_array>7)
filter

array([[False, False],
       [False, False],
       [ True,  True]], dtype=bool)

In [10]:
#Now we can select those elements which meet that criteria
print(an_array[filter])

[8 9]


In [16]:
#For short, we could have just used approach below without the need for the
an_array[(an_array % 2 ==0) & (an_array <5)]

array([4])

In [18]:
#what is particullar useful is that we can actually change elements in the array applying a similar logical filter.
an_array[an_array%2==0]+=100
an_array

array([[  1,   3],
       [204,   5],
       [208,   9]])