#  ndarray Datatypes and Operations

In [8]:
import numpy as np

In [9]:
ex1= np.array([11,12])
print (ex1.dtype)

int32


In [10]:
ex2= np.array([11.0,12.0])
print (ex2.dtype)

float64


In [11]:
ex3=np.array([11,21],dtype=np.int64)
print (ex3.dtype)

int64


In [12]:
ex4= np.array ([11.1,12.7], dtype=np.int64)
print (ex4.dtype)

int64


In [13]:
ex5=np.array([11,21],dtype=np.float64)
print (ex5.dtype)

float64


# Arithmetic Array Operations

In [23]:
x= np.array([[111,112],[121,122]],dtype=np.int)

y= np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)
print (x,"\n \n",y)

[[111 112]
 [121 122]] 
 
 [[ 211.1  212.1]
 [ 221.1  222.1]]


In [32]:
#add
print (type(x+y))
print (x+y)

<class 'numpy.ndarray'>
[[ 322.1  324.1]
 [ 342.1  344.1]]


In [31]:
print(type(np.add(x,y)))
print (np.add(x,y))

<class 'numpy.ndarray'>
[[ 322.1  324.1]
 [ 342.1  344.1]]


In [34]:
#subtract
print (type(x-y))
print (x-y)
print(type(np.subtract(x,y)))
print (np.subtract(x,y))

<class 'numpy.ndarray'>
[[-100.1 -100.1]
 [-100.1 -100.1]]
<class 'numpy.ndarray'>
[[-100.1 -100.1]
 [-100.1 -100.1]]


In [35]:
#divide
print (type(x/y))
print (x/y)
print(type(np.divide(x,y)))
print (np.divide(x,y))

<class 'numpy.ndarray'>
[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]
<class 'numpy.ndarray'>
[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [39]:
#multiply
print (type(x*y))
print (x*y)
print(type(np.multiply(x,y)))
print (np.multiply(x,y))

<class 'numpy.ndarray'>
[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]
<class 'numpy.ndarray'>
[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [40]:
#square root
print(np.sqrt(x))

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


In [41]:
#exponent (e ** x)
print(np.exp(x))

[[  1.60948707e+48   4.37503945e+48]
 [  3.54513118e+52   9.63666567e+52]]
