# Broadcasting - python for data science


In [1]:
import numpy as np

In [2]:
# Broadcasting help make your array operations more convinient 

In [5]:
start = np.zeros((4,3))
start

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
add_rows=np.array([1,0,2])
add_rows

array([1, 0, 2])

In [8]:
y= start+ add_rows #add each row of 'start' using broadcasting 
y

array([[ 1.,  0.,  2.],
       [ 1.,  0.,  2.],
       [ 1.,  0.,  2.],
       [ 1.,  0.,  2.]])

In [16]:
#create an array which is 4x1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols= add_cols.T #ĐẢo ngược array
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [17]:
#add to each column of 'start' using broadcasting 
y= start+add_cols
y

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [20]:
#this will just broadcast both dimensions
add_scalar= np.array([1]) #ko gioi han ve chieu cac thu
print(add_scalar+start)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [21]:
a = np.array([[0,0],[0,0]])
a

array([[0, 0],
       [0, 0]])

In [33]:
b1 = np.array([1,1])
b1=b1
b1

array([1, 1])

In [34]:
b2=1
b2

1

In [35]:
a+b1 == a+b2 

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [36]:
a+b1

array([[1, 1],
       [1, 1]])

In [37]:
a+b2

array([[1, 1],
       [1, 1]])