# Numpy Statistical, Sorting, and Set Operations - Python for data science

In [1]:
import numpy as np

In [4]:
#setup a random 2 x 4 matrix
arr=10 * np.random.randn(2,4)
arr

array([[-14.29092994,  12.40416083,   3.40035838,   8.36614133],
       [ 19.60396201,   3.10879124,  -2.01672173,  20.13329394]])

In [16]:
#compute the mean()
arr.mean() # == np.mean(arr)

6.3386320080074192

In [7]:
#compute the mean by row
arr.mean(axis=1)

array([  2.46993265,  10.20733136])

In [8]:
#compute the mean by collumn
arr.mean(axis=0)

array([  2.65651604,   7.75647603,   0.69181833,  14.24971763])

In [17]:
#compute the mean by collumn
np.median(arr, axis=0)

array([  2.65651604,   7.75647603,   0.69181833,  14.24971763])

In [11]:
#sum all the elements
arr.sum()

50.709056064059354

In [13]:
arr.dtype

dtype('float64')

- Mean là từ mà ta thường dùng để chỉ trung bình theo đúng nghĩa đen thông dụng, có được khi ta cộng tất cả các phần tử trong một tập hợp đang xét lại rồi chia đều cho số lượng phần tử.
- Median là giá trị giữa (middle) trong một tập hợp các phần tử, giá trị. Median thông thường được tìm bằng các bước như sau:
             + Với tập hợp cần tìm Median ta tiến hành sắp xếp chúng theo một thứ tự nhất định, ví dụ nếu là tập các số nguyên thì ta xếp theo thứ tự giá trị số tăng dần.
             + Lấy ra số ở vị trí giữa (middle), đó là median. Trong trường hợp không có vị trí chính xác giữa ta có thể xét lấy median một cách tương đối. Vì dụ với tập số nguyên, nếu số lượng phần tử chẳn, vậy sẽ không có 1 vị trí giữa, nên ta lấy Mean của 2 phần tử nằm giữa làm Median.
- Mode là giá trị xuất hiện thường xuyên nhất trong tập hợp, danh sách các giá trị, phần tử. Trong trường hợp không có giá trị nào được lặp lại thì không có Mode.
- Range là sự khác biệt, khoảng cách giữa phần tử dưới và phần tử trên, giữa giá trị nhỏ nhất (Min) với giá trị lớn nhất (Max) trong tập hợp.

# Sorting

In [19]:
unsorted= np.random.randn(10)
unsorted

array([-0.77037482,  0.12109634, -0.78168494, -0.53482797,  0.56825474,
       -0.79230797, -0.07976405, -0.89164296,  0.77325689, -1.97544816])

In [25]:
sorted= np.array(unsorted)
sorted.sort()
sorted

array([-1.97544816, -0.89164296, -0.79230797, -0.78168494, -0.77037482,
       -0.53482797, -0.07976405,  0.12109634,  0.56825474,  0.77325689])

In [27]:
unsorted.sort()
unsorted

array([-1.97544816, -0.89164296, -0.79230797, -0.78168494, -0.77037482,
       -0.53482797, -0.07976405,  0.12109634,  0.56825474,  0.77325689])

# Finding Unique elements


In [30]:
#Unique: hàm để hiện các số có trong Array, ko bị lặp
array= np.array([1,2,1,4,5,2,1,4,2])
print(np.unique(array))

[1 2 4 5]


In [33]:
# Set operations with np.array data type
s1= np.array(['desk','chair','bulb'])
s2= np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [35]:
#Giao cua 2 array: intersect, become 1d array
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [36]:
#union
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [38]:
#setdifferent 
print (np.setdiff1d(s1,s2))

['desk']


In [40]:
print(np.in1d(s1,s2)) #so sanh 2 array o cung vi tri co giong nhau ko, neu cos la True

[False  True  True]
