# NOTICED THAT IS COPIED IN NUMPY

In [1]:
import numpy as np

In [2]:
#Rank 2 arrray of shape (3,4)
an_array=np.array([[11,15,16,15],[21,13,16,10],[31,33,35,37]])

In [3]:
an_array

array([[11, 15, 16, 15],
       [21, 13, 16, 10],
       [31, 33, 35, 37]])

In [9]:
a_slice= an_array[:2,1:4]
print(a_slice)

[[15 16 15]
 [13 16 10]]


In [10]:
ba_phan_tu = an_array[:,1:3]
print(ba_phan_tu)

[[15 16]
 [13 16]
 [33 35]]


In [11]:
    print("Before", an_array)
    ba_phan_tu[0,0]=77
    print("After",an_array)

Before [[11 15 16 15]
 [21 13 16 10]
 [31 33 35 37]]
After [[11 77 16 15]
 [21 13 16 10]
 [31 33 35 37]]



=) It means that when you modify a slice, you actualy modify the underlying array!!!!!!!


In [12]:
#Copy ko bị đổi, ko liên quan đến mảng gốc
#Rank 2 arrray of shape (3,4)
an_array1=np.array([[11,15,16,15],[21,13,16,10],[31,33,35,37]])
a_slice1=np.array(an_array1[:2,1:4])
print(a_slice1)

[[15 16 15]
 [13 16 10]]


In [13]:
print("Before", an_array1)
a_slice1[0,0]=77
print("After",an_array1)

Before [[11 15 16 15]
 [21 13 16 10]
 [31 33 35 37]]
After [[11 15 16 15]
 [21 13 16 10]
 [31 33 35 37]]


Here are what we copied about!

# USE BOTH INTERGER INDEXING AND SLICE INDEXING

In [14]:
#Rank 2 arrray of shape (3,4)
an_array2=np.array([[11,15,16,15],[21,13,16,10],[31,33,35,37]])
print(an_array2)

[[11 15 16 15]
 [21 13 16 10]
 [31 33 35 37]]


In [15]:
#using both integer indexing and slicing generates an array of lower rank 

In [19]:
row_rank1= an_array[1,:]
print(row_rank1,row_rank1.shape)

[21 13 16 10] (4,)


Notice only a single []

In [62]:
#Sciling alone: generates an array of the same rank as the an_array
row_rank2=an_array[1:2,:]
print(row_rank2,row_rank2.shape)

[[21 13 16 10]] (1, 4)


Notice the [ [ ] ]

In [63]:
a = np.arange(15).reshape(3, 5)

In [64]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
#Here we'll do the same thing for the columns of the array.

In [69]:
col_rank1 = an_array2[:,1]
col_rank2 = an_array2[:,1:2]
print(col_rank1,col_rank1.shape,"\n\n", col_rank2,col_rank2.shape)

[15 13 33] (3,) 

 [[15]
 [13]
 [33]] (3, 1)


In [73]:
a = np.arange(49).reshape(7, 7)
col_rank3 = a[0:7,1:6]
print(col_rank3,col_rank3.shape)

[[ 1  2  3  4  5]
 [ 8  9 10 11 12]
 [15 16 17 18 19]
 [22 23 24 25 26]
 [29 30 31 32 33]
 [36 37 38 39 40]
 [43 44 45 46 47]] (7, 5)


Vậy chứng tỏ là chỉ có Rank 2 là max :) 

# Array Indexing for changing elements

sometimes it's useful to use array of indexes to access or change elements

In [79]:
#create a new array
an_array = np.array([[11,12,13],[22,23,24],[33,34,35],[44,45,46]])
print("Original array: \n",an_array)

Original array: 
 [[11 12 13]
 [22 23 24]
 [33 34 35]
 [44 45 46]]


In [81]:
#create an array of indicies
col_indicies=np.array([0,1,2,0])
row_indicies=np.arange(4)
print("Col indicies picked: ",col_indicies,"\nRow indicies picked: ",row_indicies)

Col indicies picked:  [0 1 2 0] 
Row indicies picked:  [0 1 2 3]


In [82]:
for row,col in zip(row_indicies,col_indicies):
    print (row,"  ",col)

0    0
1    1
2    2
3    0


OKAY now let's inspect the contents at those pairs of indices and we'll get back

In [83]:
#select one element from each row
print ("Values in the array at these indicies: ",an_array[row_indicies,col_indicies])

Values in the array at these indicies:  [11 23 35 44]


Col indicies picked:  [0 1 2 0] 
Row indicies picked:  [0 1 2 3]
    it means 0-0, 1-1, 2-2, 0-3

In [84]:
#change one element from each row using the indicies selected
an_array[row_indicies,col_indicies]+=100000

In [85]:
print("Change array: \n",an_array)

Change array: 
 [[100011     12     13]
 [    22 100023     24]
 [    33     34 100035]
 [100044     45     46]]
